---
- name: install the required
  apk: name="{{ item }}" state=present
  with_items:
    - docker
    - py-pip

- name: install python things
  pip: name="{{ item }}" state=present
  with_items:
    - docker-compose
    - docker-py
