---

- name: make sure dnf-plugins.core installed
  dnf:
    name: dnf-plugins-core
    state: present

- name: install docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: make sure docker from distro is not installed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: install docker
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - python-docker-py
    - python-pip
