- name: add sysdig RPM key
  rpm_key: state=present key=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public

- name: add sysdig repo
  get_url: url=http://download.draios.com/stable/rpm/draios.repo dest=/etc/yum.repos.d/draios.repo

- name: install linux-headers
  yum: name='kernel-devel' state=present

- name: install sysdig
  yum: name=sysdig state=present
