---
# CentOS 7 Stack Amsible
# # Author: Sathiyarajan M
# # Version: 1.0
#

#- name: Installing elasticsearch in CentOS 7
#  hosts: dbservers
#  remote_user: root
#  roles:
#   -  hadoop

#- name: Installing hadoop 2.x
#  hosts: localhost
#  become: yes
#  vars:
#    namenode_ip: localhost
#    datanode_ip: localhost
#    version: '2.8.0'
#  roles:
#    - { role: 'hadoop', hadoop_master: '{{namenode_ip}}', hadoop_type_of_node: 'master', hadoop_version: '{{version}}' }
#    - { role: 'hadoop', hadoop_master: '{{datanode_ip}}', hadoop_version: '{{version}}' }

- hosts: all
  user: vagrant
  sudo: true
  roles: 
    - hadoop
- name: Installing elasticsearch in CentOS 7
  hosts: zookeeper-nodes
  remote_user: root
  roles:
    -  zookeeper
- name: Installing elasticsearch in CentOS 7
  hosts: dbservers
  remote_user: root
  roles:
    -  kafka
    
- name: Installing elasticsearch in CentOS 7
  hosts: dbservers
  remote_user: root
  roles:
    -  spark

#- name: Installing hadoop 2.x
#  hosts: localhost
#  become: yes
#  vars:
#    namenode_ip: localhost
#    datanode_ip: localhost
#    version: '2.8.0'
#  roles:
#    - { role: 'hadoop', hadoop_master: '{{namenode_ip}}', hadoop_type_of_node: 'master', hadoop_version: '{{version}}' }
#    - { role: 'hadoop', hadoop_master: '{{datanode_ip}}', hadoop_version: '{{version}}' }
